//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BePreferenceCentre.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEMailingList
    {
        public int MailingListsId { get; set; }
        public string ListId { get; set; }
        public string ListName { get; set; }
        public int MemberCount { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public bool ShowUser { get; set; }
        public string ImageURL { get; set; }
    }
}
