//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BePreferenceCentre.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BePreferencesEntities : DbContext
    {
        public BePreferencesEntities()
            : base("name=BePreferencesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BEMailingList> BEMailingLists { get; set; }
        public virtual DbSet<BEMemberList> BEMemberLists { get; set; }
        public virtual DbSet<InkeyProductTag> InkeyProductTags { get; set; }
        public virtual DbSet<InkeyUserQuestion> InkeyUserQuestions { get; set; }
        public virtual DbSet<InkeyAnswer> InkeyAnswers { get; set; }
        public virtual DbSet<InkeyProduct> InkeyProducts { get; set; }
    }
}
