//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BePreferenceCentre.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InkeyUserQuestion
    {
        public int InkeyUserQuestionsId { get; set; }
        public string UserQuestion { get; set; }
        public System.DateTime Created { get; set; }
    }
}
