//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BePreferenceCentre.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InkeyProduct
    {
        public int InkeyProductsId { get; set; }
        public string ProductName { get; set; }
        public string ProductImageLink { get; set; }
        public string ProductLink { get; set; }
        public string PhoneticName { get; set; }
    }
}
