//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BePreferenceCentre.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InkeyStoresU
    {
        public string StoreName { get; set; }
        public string Region { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public int InkeyStoresUSId { get; set; }
        public string StoreRegion { get; set; }
        public string Store { get; set; }
    }
}
